# Generated by Django 5.1.2 on 2024-11-27 15:57

import shop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_product_base_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='temp_name',
            field=models.CharField(default='', max_length=50, verbose_name='Видимое название'),
        ),
        migrations.AlterField(
            model_name='additionaloption',
            name='addi_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='categoryimage',
            name='image',
            field=models.ImageField(null=True, upload_to=shop.models.category_images_dir),
        ),
    ]
