# Generated by Django 5.1.2 on 2024-12-01 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_category_temp_name_alter_additionaloption_addi_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='products_description',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Общее описание товаров внутри категории'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Краткое описание в выборе категорий'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Индивидуальное описание товара'),
        ),
    ]
