# Generated by Django 5.1.2 on 2024-12-04 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_category_products_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='additional_options',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size_options',
        ),
        migrations.AlterField(
            model_name='additionaloption',
            name='products',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='add_options', to='shop.product'),
        ),
        migrations.AlterField(
            model_name='sizeoption',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='shop.product'),
        ),
    ]
