# Generated by Django 5.1.2 on 2024-12-08 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_remove_product_additional_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='price',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='price',
            name='product',
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.CreateModel(
            name='HandleOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handle_name', models.CharField(max_length=100)),
                ('price_increase', models.DecimalField(decimal_places=0, max_digits=5)),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handle_options', to='shop.product')),
            ],
        ),
        migrations.DeleteModel(
            name='AdditionalOption',
        ),
        migrations.DeleteModel(
            name='Price',
        ),
    ]
