# Generated by Django 5.1.2 on 2024-12-17 18:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_price_unique_together_remove_price_product_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('threshold', models.CharField(choices=[('да', 'Да'), ('нет', 'Нет')], max_length=3)),
                ('opening_side', models.CharField(max_length=50)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('handle_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.handleoption')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
                ('size_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.sizeoption')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('session_key', 'product', 'size_option', 'handle_option', 'threshold', 'opening_side')},
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('threshold', models.CharField(choices=[('да', 'Да'), ('нет', 'Нет')], max_length=3)),
                ('opening_side', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('handle_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.handleoption')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
                ('size_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.sizeoption')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('session_key', 'product', 'size_option', 'handle_option', 'threshold', 'opening_side')},
            },
        ),
    ]
