# Generated by Django 5.1.2 on 2024-12-18 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_cart_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='threshold',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
