# Generated by Django 5.1.2 on 2024-12-18 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_favorite_added_at_alter_favorite_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
