# Generated by Django 5.1.2 on 2024-12-22 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_cart_added_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='air_gap',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='favorite',
            name='box_size',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='favorite',
            name='glass_size',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
