# Generated by Django 5.1.2 on 2024-12-24 02:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_favorite_air_gap_favorite_box_size_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('delivery_method', models.CharField(choices=[('company1', 'ТК Деловые линии'), ('company2', 'ТК КИТ'), ('company3', 'ТК Байкал-Сервис'), ('company99', 'Сборный груз (проходящая машина), для близлежащих регионов'), ('custom', 'Другая компания')], max_length=60)),
                ('custom_delivery', models.CharField(blank=True, max_length=200, null=True)),
                ('payment_method', models.CharField(choices=[('card', 'Оплата картой на сайте'), ('transfer_to_card', 'Оплата переводом на карту'), ('bank_transfer_with_VAT', 'Банковский перевод с НДС'), ('bank_transfer_without_VAT', 'Банковский перевод без НДС'), ('card_in_office', 'Картой в офисе'), ('cash', 'Наличные в офисе')], max_length=30)),
                ('address', models.TextField()),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('processing', 'В обработке'), ('agreement', 'Заключение договора'), ('paid', 'В работе'), ('ready', 'Готов, ожидает отгрузку'), ('shipped', 'Отгружен')], default='processing', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threshold', models.CharField(choices=[('да', 'Да'), ('нет', 'Нет')], max_length=3)),
                ('opening_side', models.CharField(max_length=50)),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('handle_option', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.handleoption')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.product')),
                ('size_option', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.sizeoption')),
            ],
        ),
    ]
