# Generated by Django 5.1.2 on 2024-12-24 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_order_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('company1', 'ТК Деловые линии'), ('company2', 'ТК КИТ'), ('company3', 'ТК Байкал-Сервис'), ('company4', 'Самовывоз'), ('company99', 'Сборный груз (проходящая машина), для близлежащих регионов'), ('custom', 'Другая компания')], max_length=60),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Оплата по QR коду'), ('transfer_to_card', 'Оплата переводом на карту'), ('bank_transfer_with_VAT', 'Банковский перевод с НДС'), ('bank_transfer_without_VAT', 'Банковский перевод без НДС'), ('card_in_office', 'Оплата картой в офисе'), ('cash', 'Оплата наличными в офисе')], max_length=30),
        ),
    ]
