# Generated by Django 5.1.2 on 2024-12-24 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_alter_order_delivery_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('company1', 'ТК Деловые линии'), ('company2', 'ТК КИТ'), ('company3', 'ТК Байкал-Сервис'), ('company4', 'Самовывоз'), ('company99', 'Сборный груз (проходящая машина), для близлежащих регионов'), ('custom', 'Другой вариант')], max_length=60),
        ),
    ]
