version: '3.8'

services:
  web:
    build: .
    container_name: django_app
    command: gunicorn artadoors.wsgi:application -b 0.0.0.0:8000 --workers 3 --timeout 120
    volumes:
      - .:/code
      - static_volume:/code/static  # Статика
      - media_volume:/code/media    # Медиафайлы
    ports:
      - "8000:8000"
    networks:
      - web-network
    environment:
      - DJANGO_SETTINGS_MODULE=artadoors.settings.prod

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/code/static  # Используем тот же том, что и в Django
      - media_volume:/code/media    # Используем тот же том, что и в Django
    depends_on:
      - web
    networks:
      - web-network

volumes:
  static_volume:
  media_volume:

networks:
  web-network:
    driver: bridge