name: Deploy to Web Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Debug SSH connection
        run: |
          ssh -v -o StrictHostKeyChecking=no server@skwortsoff.twilightparadox.com 'echo "SSH connection successful"'

      - name: Update repository on server
        run: |
          ssh server@skwortsoff.twilightparadox.com 'cd /home/server/project && git pull origin master' 

      - name: Restart Docker containers
        run: |
          ssh server@skwortsoff.twilightparadox.com << 'EOF'
          cd /home/server/project/artadoors
          docker compose down
          docker compose up -d --build
          EOF
