name: Deploy to Web Server

on:
  push:
    branches:
      - master  # Указываем ветку master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Update repository on server
        run: |
          ssh server@deb-server 'cd /home/server/project && git pull origin master'
