name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r artadoors/requirements/dev.txt
      
      
      - name: Create .env file for tests
        run: |
          cat <<EOF > artadoors/.env
          SECRET_KEY=$(python -c 'from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())')
          EOF
      
      - name: Run migrations
        run: |
          python artadoors/manage.py migrate --settings=artadoors.settings.test

      - name: Run tests
        run: |
          pytest artadoors/shop/tests


  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Debug SSH connection
        run: |
          ssh -v -o StrictHostKeyChecking=no server@skwortsoff.twilightparadox.com 'echo "SSH connection successful"'

      - name: Update repository on server
        run: |
          ssh server@skwortsoff.twilightparadox.com 'cd /home/server/project && git pull origin master' 

      - name: Restart Docker containers
        run: |
          ssh server@skwortsoff.twilightparadox.com << 'EOF'
          cd /home/server/project/artadoors
          docker compose down
          docker compose up -d --build
          docker cp /home/server/project/artadoors/media/. nginx_proxy:/code/media/
          docker restart nginx_proxy
          EOF
